export const projectsData = [
  {
    id: "project1",
    title: "soukrak.com",
    descriptionKey: "project1",
    img: "/souk_rak.png",
    width: 225,
    height: 225,
    dateKey: "project1Date",
    href: "https://soukrak.com",
  },
  {
    id: "project2",
    title: "doctori.org",
    descriptionKey: "project2",
    dateKey: "project2Date",
    href: "https://doctori.vercel.app/",
  },
  {
    id: "project3",
    title: "teamsoft.net",
    descriptionKey: "project3",
    img: "/team_soft.png",
    width: 125,
    height: 125,
    dateKey: "project3Date",
    href: "https://team-soft.vercel.app/",
  },
  {
    id: "project4",
    title: "talhaoui.me",
    img: "/favicon.png",
    width: 40,
    height: 40,
    descriptionKey: "project4",
    dateKey: "project4Date",
    href: "https://hoobank-website.vercel.app/",
  },
  {
    id: "project5",
    title: "rexo.tech",
    descriptionKey: "project5",
    dateKey: "project5Date",
    href: "rexo.tech",
  },
];
